--Giving Real Pizza SQL Scripts

INSERT INTO REAL_PIZZA(REAL_PIZZA_ID, REAL_BASE_PRICE, REAL_PIZZA_NAME ) VALUES (1, 100, 'Mexican Wave');
INSERT INTO REAL_PIZZA(REAL_PIZZA_ID, REAL_BASE_PRICE, REAL_PIZZA_NAME ) VALUES (2, 200, 'Deluxe Veggie');
INSERT INTO REAL_PIZZA(REAL_PIZZA_ID, REAL_BASE_PRICE, REAL_PIZZA_NAME ) VALUES (3, 300, 'Peppy Panner');
INSERT INTO REAL_PIZZA(REAL_PIZZA_ID, REAL_BASE_PRICE, REAL_PIZZA_NAME ) VALUES (4, 200, 'Chicken Golden');
INSERT INTO REAL_PIZZA(REAL_PIZZA_ID, REAL_BASE_PRICE, REAL_PIZZA_NAME ) VALUES (5, 300, 'NonVeg Supreme');

--Giving Size Scripts

INSERT INTO PIZZA_SIZES(SIZE_ID, SIZE_NAME, SIZE_PRICE) VALUES (1, 'small', 0.0);
INSERT INTO PIZZA_SIZES(SIZE_ID, SIZE_NAME, SIZE_PRICE) VALUES (2, 'medium', 100.0);
INSERT INTO PIZZA_SIZES(SIZE_ID, SIZE_NAME, SIZE_PRICE) VALUES (3, 'large', 150.0);

--Giving Toppings

INSERT INTO TOPPINGS(TOPPINGS_ID, TOPPINGS_NAME, TOPPINGS_PRICE ) VALUES(1, 'pepperoni', 30);
INSERT INTO TOPPINGS(TOPPINGS_ID, TOPPINGS_NAME, TOPPINGS_PRICE ) VALUES(2, 'mushrooms', 30);
INSERT INTO TOPPINGS(TOPPINGS_ID, TOPPINGS_NAME, TOPPINGS_PRICE ) VALUES(3, 'olives', 30);
INSERT INTO TOPPINGS(TOPPINGS_ID, TOPPINGS_NAME, TOPPINGS_PRICE ) VALUES(4, 'red onions', 30);
INSERT INTO TOPPINGS(TOPPINGS_ID, TOPPINGS_NAME, TOPPINGS_PRICE ) VALUES(5, 'green peppers', 30);
INSERT INTO TOPPINGS(TOPPINGS_ID, TOPPINGS_NAME, TOPPINGS_PRICE ) VALUES(6, 'banana peppers', 30);
INSERT INTO TOPPINGS(TOPPINGS_ID, TOPPINGS_NAME, TOPPINGS_PRICE ) VALUES(7, 'jalapeno peppers', 30);
INSERT INTO TOPPINGS(TOPPINGS_ID, TOPPINGS_NAME, TOPPINGS_PRICE ) VALUES(8, 'artichokes', 30);
INSERT INTO TOPPINGS(TOPPINGS_ID, TOPPINGS_NAME, TOPPINGS_PRICE ) VALUES(9, 'sun-dried tomatoes', 30);
INSERT INTO TOPPINGS(TOPPINGS_ID, TOPPINGS_NAME, TOPPINGS_PRICE ) VALUES(10, 'basil', 30);


--Giving Discount

INSERT INTO DISCOUNT(DISCOUNT_ID, DISCOUNT_PERCENTAGE, DISCOUNT_NAME ) VALUES(1, 10, 'Flat 10% off');